### ISSUE TITLE
twitterのリンクが間違っている気がする

### ISSUE THREAD

**Issue by hand-dot** [andoshin11/studio-andy#114]
はじめまして！
nuxt関連でブログがヒットし、みていたのですがフッターのリンクからツイッターに飛べなかったので、報告ですw

https://github.com/andoshin11/studio-andy/blob/831f262e06319928d673d20a50c15cbfbcac51b8/packages/studio-andy-app/src/containers/Footer/Footer.tsx#L15

**Comment by andoshin11** [comment]
@hand-dot ご指摘ありがとうございました 🙇 こちら下記にて修正とさせていただきました。issueいただけて嬉しいです！

https://github.com/andoshin11/studio-andy/pull/116
